:project_name: Name des Projekts
:toc: left
:numbered:
= Pflichtenheft __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren(en) |  Vermerk
|0.1     | In Arbeit   | 01.04.2023          | Autor       | Initiale Version
|===

== Inhaltsverzeichnis
Dieses Dokument benötigt ein Inhaltsverzeichnis. Es existieren mehrere Einbindungsmöglichkeiten.

== Zusammenfassung
Eine kurze Beschreibung des Dokuments. Wenige Absätze.

== Aufgabenstellung und Zielsetzung
Text aus Aufgabenstellung kopieren und ggfs. präzisieren.
Insbesondere ergänzen, welche Ziele mit dem Abschluss des Projektes erreicht werden sollen.

== Produktnutzung
In welchem Kontext soll das System später genutzt werden? Welche Rahmenbedingungen gelten?
Zusätzlich kurze Einleitung für fachfremde Personen

== Interessensgruppen (Stakeholder)
Welche realen und juristischen Personen(-gruppen) haben Einfluss auf die Anforderungen im Projekt?

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

== Anwendungsfälle

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).
Weitere relevante Spalten können bei Bedarf ergänzt werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name |Beschreibung
|...  |...
|===

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

== Funktionale Anforderungen

=== Muss-Kriterien
Was das zu erstellende Programm auf alle Fälle leisten muss.

=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

== Nicht-Funktionale Anforderungen

=== Qualitätsziele

Dokumentieren Sie in einer Tabelle die Qualitätsziele, welche das System erreichen soll, sowie deren Priorität.

=== Konkrete Nicht-Funktionale Anforderungen

Beschreiben Sie Nicht-Funktionale Anforderungen, welche dazu dienen, die zuvor definierten Qualitätsziele zu erreichen.
Achten Sie darauf, dass deren Erfüllung (mindestens theoretisch) messbar sein muss.

== GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Akzeptanztestfälle

[cols="1h, 4"]
|===
|ID            |[[AT0001]]<<AT0001>>
|Funktionale Anforderung | [[F4]] <<F4>>  , [[F6]] <<F6>> ,[[F7]] <<F7>>,[[F13]] <<F13>>,[[F14]] <<F14>>,[[F15]] <<F15>>
|Use Case      |[[UC001]] <<UC001>> Rezept einlösen
|Vorbedingung(en)      a|Der Kunde hat ein gültiges Rezept und steht am Apothekenschalter.
|Ablauf      a|
Der Kunde übergibt ein Rezept mit folgendem Inhalt: +
 - *Patient:* Max Meier +
 - *Geburtsdatum:* 01.02.1980 +
 - *Medikament:* Ibuprofen 400mg, 20 Tabletten +
  Der Apothekenmitarbeiter überprüft das Rezept. +
  Das System prüft die Verfügbarkeit: +
 - Wenn vorrätig: Ausgabe direkt an den Kunden. +
 - Wenn nicht: Ein Bestellzettel mit ID wird erstellt.
|Ergebnis(se)     a|
 - Medikament wurde ausgegeben oder vorgemerkt +
 - Zuzahlung bei Kassenpatienten berechnet +
 - Ausgabe im System gespeichert zur späteren Abrechnung mit der Krankenkasse
|===

[cols="1h, 4"]
|===
|ID            |[[AT0002]]<<AT0002>>
|Funktionale Anforderung |[[F17]] <<F17>>
|Use Case      | [[UC002]] <<UC002>> Medikamente nachbestellen
|Vorbedingung(en)      a|Der Apothekenmitarbeiter verkauft ein Medikament.
|Ablauf      a|
Ein Kunde kauft *Paracetamol 500mg*. +
Beim Scannen erkennt das System, dass nur noch 2 Packungen auf Lager sind (unter Mindestbestand). +
Das Medikament wird automatisch zur Nachbestellung vorgemerkt und vom System bestellt.
|Ergebnis(se)     a|
- Medikament wurde erfolgreich zur Nachbestellung vorgemerkt +
- Bestellung im System dokumentiert
|===

[cols="1h, 4"]
|===
|ID            |[[AT0003]]<<AT0003>>
|Funktionale Anforderung |[[F1]] <<F1>>,[[F2]] <<F2>>,[[F7]] <<F7>>,[[F16]] <<F16>>
|Use Case      | [[UC003]] <<UC003>> Zugang mit Username und Password

|Vorbedingung(en)      a|Eine registrierte Arzthelferin befindet sich am Eingang zur Apotheke.
|Ablauf      a|
Arzthelferin  gibt die Username und Password  ein. +
 -  Name: TestCustomer +
 - Passwort: 123 +
Das System prüft die Berechtigung und ob ein anderer Zugriff aktiv ist. +
Tür öffnet sich. Medikamente *Insulin und Verbandmaterial* werden entnommen.
|Ergebnis(se)     a|
- Zugang gewährt +
- Entnahme dokumentiert und zugeordnet
|===

[cols="1h, 4"]
|===
|ID            |[[AT0004]]<<AT0004>>
|Funktionale Anforderung |[[F11]] <<F11>>,[[F12]] <<F12>>
|Use Case      |[[UC004]] <<UC004>> Verfallene Medikamente erkennen
|Vorbedingung(en)      a|Wöchentliche Prüfung durch das System aktiviert
|Ablauf      a|
Am Montag startet die automatische Prüfung. +
Das System erkennt, dass *3 Packungen Amoxicillin* abgelaufen sind. +
Liste wird erzeugt und dem Mitarbeiter angezeigt.
|Ergebnis(se)     a|
- Liste mit verfallenen Medikamenten angezeigt +
- Medikamente wurden entfernt
|===

[cols="1h, 4"]
|===
|ID            |[[AT0005]]<<AT0005>>
|Funktionale Anforderung |<<F16>>
|Use Case      |[[UC005]] <<UC005>> Abrechnung mit Zentralkasse
|Vorbedingung(en)      a|Monatsende ist erreicht, alle Verkäufe dokumentiert
|Ablauf      a|
Am 30.06. wird die monatliche Abrechnung gestartet. +
Das System erstellt automatisch eine Sammelabrechnung für alle Kassenpatienten und übermittelt sie digital an die Krankenkasse.
|Ergebnis(se)     a|
- Abrechnung versendet +
- Empfangsbestätigung wird gespeichert
|===

[cols="1h, 4"]
|===
|ID            |[[AT0006]]<<AT0006>>
|Funktionale Anforderung |[[F8]] <<F8>>,[[F9]] <<F9>>, <<F14>>, <<F15>>
|Use Case      |[[UC006]] <<UC006>> Spezialpräparat anfordern
|Vorbedingung(en)      a|Kunde möchte eine individuelle Salbe bestellen
|Ablauf      a|
Kunde bestellt *Heilsalbe mit 20g Zinkoxid*. +
Apothekenmitarbeiter erfasst die Bestellung, erstellt einen Bestellzettel mit ID *#...*. +
Die Mixtur wird im Labor hergestellt und im System als "abholbereit" markiert.
|Ergebnis(se)     a|
- Bestellung dokumentiert +
- Rezeptur erstellt +
- Abholung möglich
|===

[cols="1h, 4"]
|===
|ID            |[[AT0007]]<<AT0007>>
|Funktionale Anforderung |[[F18]]  <<F18>>,[[F19]] <<F19>>,[[F20]] <<F20>>
|Use Case      |[[UC007]] <<UC007>> Medikamente ausliefern
|Vorbedingung(en)      a|Bestellung mit Adresse liegt vor
|Ablauf      a|
Lieferdienst übernimmt Bestellung für  *Kunden* +
Route wird geplant, Medikamente verpackt und ausgeliefert.
|Ergebnis(se)     a|
- Medikamente ausgeliefert +
- Lieferung im System bestätigt
|===

[cols="1h, 4"]
|===
|ID            |[[AT0008]]<<AT0008>>
|Funktionale Anforderung |<<F6>>,[[F10]] <<F10>>,
|Use Case      |[[UC008]] <<UC008>> Medikament kaufen
|Vorbedingung(en)      a|Ein Kunde steht mit einem Medikament an der SB-Kasse oder an der regulären Kasse.
|Ablauf      a|
- Der Kunde legt *Aspirin 100mg* zur Bezahlung vor. +
- Fall A: Der Kunde nutzt die *SB-Kasse*. +
- Fall B: Der Kunde geht zur *normalen Kasse*. +

Der Apothekenmitarbeiter (bei Fall B) oder das System (bei Fall A) scannt den Strichcode. +

Zahlungsoptionen: +
- *Barzahlung:* Der Kunde zahlt den vollen Betrag in bar (z. B. 4,99 €). +
- *Kassenpatient:* Der Kunde zahlt nur die gesetzliche Zuzahlung (z. B. 5 €). Der Restbetrag wird mit der Zentralkasse abgerechnet.

Anschließend wird automatisch eine Quittung erstellt.
|Ergebnis(se)     a|
- Zahlung abgeschlossen +
- Quittung ausgestellt +
- Medikament wurde ausgegeben +
- Lagerbestand wurde aktualisiert +
- Daten zur Abrechnung mit der Krankenkasse wurden gespeichert
|===


== Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten
Stakeholder essenziell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
