@startuml
actor Arzt
participant Apothekenmitarbeiter
participant "Apotheken-Computer"

Arzt -> Apothekenmitarbeiter : Spezialpräparat anfordern
Apothekenmitarbeiter -> "Apotheken-Computer" : Auftrag erfassen
"Apotheken-Computer" -> "Apotheken-Computer" : Auftrag dokumentieren
Apothekenmitarbeiter -> Apothekenmitarbeiter : Präparat im Laborbereich herstellen
Apothekenmitarbeiter -> Arzt : Präparat abholbereit melden
@enduml
