
@startuml
actor Kunde
participant Apothekenmitarbeiter
participant "Apotheken-Computer"
participant Datenbank

 Kunde --> Apothekenmitarbeiter : Rezept übergeben
 Apothekenmitarbeiter --> "Apotheken-Computer" :Rezept daten eingeben
 "Apotheken-Computer" -->Datenbank :  Medikamente suchen
 alt Verfügbar
 '== "verfügbar "==

 Datenbank --> "Apotheken-Computer" : verfügbarkeit bestätigen
 "Apotheken-Computer" --> Apothekenmitarbeiter :  Medikamente breitstelen
 Apothekenmitarbeiter--> Kunde :  Medikamente ausgeben
 else "nicht verfügbar"
 ' == "nicht verfügbar" ==
 "Apotheken-Computer"--> Apothekenmitarbeiter : Medikamente nicht verfügbar
   Apothekenmitarbeiter--> Kunde :  Bestellzettel mit ID übergeben
   end
@enduml
